# Artificial Neural Network

### Importing the libraries

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf


In [2]:
tf.__version__

'2.8.0'

## Part 1 - Data Preprocessing

### Importing the dataset

In [3]:
dataset = pd.read_csv('/content/Churn_Modelling.csv')
X = dataset.iloc[:, 3:-1].values
Y = dataset.iloc[:, -1].values

In [4]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [5]:
print(Y)

[1 0 1 ... 1 1 0]


### Encoding categorical data

Label Encoding the "Gender" column

In [6]:
from sklearn.preprocessing import LabelEncoder
Le = LabelEncoder()
X[:,2] = Le.fit_transform(X[:,2])


In [7]:
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


One Hot Encoding the "Geography" column

In [8]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct =  ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [9]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


### Splitting the dataset into the Training set and Test set

In [10]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X,Y, test_size=.2, random_state=2)


In [11]:
print(X_train)

[[1.0 0.0 0.0 ... 1 1 64716.08]
 [0.0 1.0 0.0 ... 1 1 131886.46]
 [1.0 0.0 0.0 ... 1 1 99661.46]
 ...
 [1.0 0.0 0.0 ... 1 0 195033.07]
 [0.0 1.0 0.0 ... 1 0 176680.16]
 [1.0 0.0 0.0 ... 1 0 151316.37]]


In [12]:
print(X_test)

[[1.0 0.0 0.0 ... 1 0 171340.68]
 [0.0 1.0 0.0 ... 1 0 129936.53]
 [1.0 0.0 0.0 ... 1 1 142400.27]
 ...
 [1.0 0.0 0.0 ... 0 0 92220.12]
 [1.0 0.0 0.0 ... 1 0 53222.15]
 [1.0 0.0 0.0 ... 0 0 102950.79]]


In [13]:
print(Y_test)

[1 1 1 ... 1 1 0]


In [14]:
print(Y_train)

[0 0 0 ... 0 1 0]


### Feature Scaling

In [15]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

## Part 2 - Building the ANN

### Initializing the ANN

In [16]:
ann =  tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [17]:
ann.add(tf.keras.layers.Dense(units=6, activation = 'relu')) 

### Adding the second hidden layer

In [18]:
ann.add(tf.keras.layers.Dense(units=6, activation = 'relu')) 

### Adding the output layer

In [19]:
ann.add(tf.keras.layers.Dense(units=1, activation = 'sigmoid')) 

## Part 3 - Training the ANN

### Compiling the ANN

In [20]:
ann.compile(optimizer='adam' , loss='binary_crossentropy' , metrics=['accuracy'])

#optimizer here use to update weights using schostic gradient desent, loss function will calculate the with every iteration and metrics will check accuracy.
#for binary classification like 0/1 , yes/no etc loss is binary_crossentropy
#for non binary classification means more than 2 then loss is categorical_crossentropy and activation for output should be softmax not sigmoid


### Training the ANN on the Training set

In [21]:
ann.fit(X_train, Y_train, batch_size= 32, epochs=100)

Epoch 1/100
250/250 [==============================] - 1s 2ms/step - loss: 0.5254 - accuracy: 0.7735
Epoch 2/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4475 - accuracy: 0.8066
Epoch 3/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4236 - accuracy: 0.8138
Epoch 4/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4103 - accuracy: 0.8195
Epoch 5/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3989 - accuracy: 0.8259
Epoch 6/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3882 - accuracy: 0.8349
Epoch 7/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3780 - accuracy: 0.8388
Epoch 8/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3696 - accuracy: 0.8449
Epoch 9/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3635 - accuracy: 0.8489
Epoch 10/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3588 - accura

## Part 4 - Making the predictions and evaluating the model

### Predicting the result of a single observation

**Homework**

Use our ANN model to predict if the customer with the following informations will leave the bank: 

Geography: France

Credit Score: 600

Gender: Male

Age: 40 years old

Tenure: 3 years

Balance: \$ 60000

Number of Products: 2

Does this customer have a credit card ? Yes

Is this customer an Active Member: Yes

Estimated Salary: \$ 50000

So, should we say goodbye to that customer ?

**Solution**

In [22]:
y_predS = ann.predict(sc.transform([[1.0, 0.0, 0.0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000 ]]))
print(y_predS > 0.5)#will give probabilty True if > 0.5 else false

[[False]]


Therefore, our ANN model predicts that this customer stays in the bank!

**Important note 1:** Notice that the values of the features were all input in a double pair of square brackets. That's because the "predict" method always expects a 2D array as the format of its inputs. And putting our values into a double pair of square brackets makes the input exactly a 2D array.

**Important note 2:** Notice also that the "France" country was not input as a string in the last column but as "1, 0, 0" in the first three columns. That's because of course the predict method expects the one-hot-encoded values of the state, and as we see in the first row of the matrix of features X, "France" was encoded as "1, 0, 0". And be careful to include these values in the first three columns, because the dummy variables are always created in the first columns.

### Predicting the Test set results

In [23]:
Y_Pred = ann.predict(X_test)
Y_Pred = (Y_Pred > 0.5)
print(np.concatenate((Y_Pred.reshape(len(Y_Pred),1), Y_test.reshape(len(Y_test),1)),1))

[[0 1]
 [1 1]
 [0 1]
 ...
 [1 1]
 [0 1]
 [0 0]]


### Making the Confusion Matrix

In [24]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(Y_test, Y_Pred)
print(cm)
accuracy_score(Y_test, Y_Pred)

[[1541   76]
 [ 201  182]]


0.8615